StarboundWorlds (Obsolete)/StarboundWorlds/Models/Moon.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace StarboundWorlds.Models
{
    public class Moon : World
    {
        public Planet ofPlanet { get; set; }

        public String MoonName { get; set; }
    }
}

StarboundWorlds (Obsolete)/StarboundWorlds/Models/Planet.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace StarboundWorlds.Models
{
    public class Planet : World
    {
        //public Moon Moons { get; set; }

        //public Moon[] Moons { get; set;  }

        public int Orbit { get; set; }

        public string PlanetName { get; set; }

        //public virtual ICollection<Moon> PlanetMoons { get; set; }
    }
}

StarboundWorlds (Obsolete)/StarboundWorlds/Models/StarSystem.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace StarboundWorlds.Models
{
    public class StarSystem
    {
        public int StarID { get; set; }
        public string StarType { get; set; }
        public int Xcoordinate { get; set; }
        public int Ycoordinate { get; set; }

        //public World[] Worlds { get; set; }

        //public virtual ICollection<World> StarWorlds { get; set; }

        public string StarName { get; set; }
    }
}

StarboundWorlds (Obsolete)/StarboundWorlds/Models/World.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace StarboundWorlds.Models
{
    public class World
    {
        public int WorldID { get; set; }
        //public StarSystem Star { get; set; }
        public string WorldType { get; set; }
        public int WorldSize { get; set; }
        public float WorldGravity { get; set; }

        //public string[] WorldFeatures { get; set; }

        //public virtual ICollection<String> WorldFeatures { get; set; }


    }
}

StarboundWorlds (Obsolete)/StarboundWorlds/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StarboundWorlds.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

StarboundWorlds (Obsolete)/StarboundWorlds/Controllers/WorldController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StarboundWorlds.DAL;
using StarboundWorlds.Models;

namespace StarboundWorlds.Controllers
{
    public class WorldController : Controller
    {
        private PrimaryContext db = new PrimaryContext();

        // GET: World
        public ActionResult Index()
        {
            return View(db.World.ToList());
        }

        // GET: World/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            World world = db.World.Find(id);
            if (world == null)
            {
                return HttpNotFound();
            }
            return View(world);
        }

        // GET: World/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: World/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "WorldID,WorldType,WorldSize,WorldGravity")] World world)
        {
            if (ModelState.IsValid)
            {
                db.World.Add(world);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(world);
        }

        // GET: World/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            World world = db.World.Find(id);
            if (world == null)
            {
                return HttpNotFound();
            }
            return View(world);
        }

        // POST: World/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "WorldID,WorldType,WorldSize,WorldGravity")] World world)
        {
            if (ModelState.IsValid)
            {
                db.Entry(world).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(world);
        }

        // GET: World/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            World world = db.World.Find(id);
            if (world == null)
            {
                return HttpNotFound();
            }
            return View(world);
        }

        // POST: World/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            World world = db.World.Find(id);
            db.World.Remove(world);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

StarboundWorlds (Obsolete)/StarboundWorlds/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

StarboundWorlds (Obsolete)/StarboundWorlds/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

StarboundWorlds (Obsolete)/StarboundWorlds/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Starbound Worlds</h1>
</div>
<div class="row">
    <div class="col-md-4">
        <h2>Welcome to Starbound Worlds</h2>
        <p>
            This site exists to give you a better experience exploring the Starbound
            Universe. Here you can use our database to catalogue worlds you explore
            in game and keep track of them in a useful fashion.
        </p>
    </div>
    <div class="col-md-4">
        <h2></h2>
        <p></p>
        <p></p>
    </div>
    <div class="col-md-4">
        <h2></h2>
        <p></p>
        <p></p>
    </div>
</div>

StarboundWorlds (Obsolete)/StarboundWorlds/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Starbound Worlds</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Starbound Worlds", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Worlds", "Index", "World")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Starbound Worlds</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

StarboundWorlds (Obsolete)/StarboundWorlds/Views/World/Create.cshtml
@model StarboundWorlds.Models.World

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>World</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.WorldType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WorldType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.WorldType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WorldSize, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WorldSize, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.WorldSize, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WorldGravity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WorldGravity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.WorldGravity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

StarboundWorlds (Obsolete)/StarboundWorlds/Views/World/Delete.cshtml
@model StarboundWorlds.Models.World

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>World</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.WorldType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WorldType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WorldSize)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WorldSize)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WorldGravity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WorldGravity)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

StarboundWorlds (Obsolete)/StarboundWorlds/Views/World/Details.cshtml
@model StarboundWorlds.Models.World

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>World</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.WorldType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WorldType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WorldSize)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WorldSize)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WorldGravity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WorldGravity)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.WorldID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

StarboundWorlds (Obsolete)/StarboundWorlds/Views/World/Edit.cshtml
@model StarboundWorlds.Models.World

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>World</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.WorldID)

        <div class="form-group">
            @Html.LabelFor(model => model.WorldType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WorldType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.WorldType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WorldSize, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WorldSize, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.WorldSize, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WorldGravity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WorldGravity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.WorldGravity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

StarboundWorlds (Obsolete)/StarboundWorlds/Views/World/Index.cshtml
@model IEnumerable<StarboundWorlds.Models.World>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.WorldType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.WorldSize)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.WorldGravity)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.WorldType)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.WorldSize)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.WorldGravity)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.WorldID }) |
            @Html.ActionLink("Details", "Details", new { id=item.WorldID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.WorldID })
        </td>
    </tr>
}

</table>