WorldsProject/WorldsProject/Controllers/MoonController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WorldsProject.Models;
using WorldsProject.DAL;

namespace WorldsProject.Controllers
{
    public class MoonController : Controller
    {
        private PrimaryContext db = new PrimaryContext();

        // GET: Moon
        public ActionResult Index()
        {
            var moons = db.Moons.Include(m => m.Planet);
            return View(moons.ToList());
        }

        // GET: Moon/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Moon moon = db.Moons.Find(id);
            if (moon == null)
            {
                return HttpNotFound();
            }
            return View(moon);
        }

        // GET: Moon/Create
        public ActionResult Create()
        {
            ViewBag.PlanetID = new SelectList(db.Planets, "PlanetID", "PlanetName");
            return View();
        }

        // POST: Moon/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PlanetID,Orbit,WorldType,WorldSize,WorldGravity,DayLength")] Moon moonVM)
        {
            if (ModelState.IsValid)
            {
                Moon newMoon = new Moon();

                newMoon.PlanetID = moonVM.PlanetID;
                newMoon.Orbit = moonVM.Orbit;

                newMoon.WorldType = moonVM.WorldType;
                newMoon.WorldSize = moonVM.WorldSize;
                newMoon.WorldGravity = moonVM.WorldGravity;
                newMoon.DayLength = moonVM.DayLength;

                //newMoon.MoonName = moonVM.inheritMoonName();

                db.Moons.Add(newMoon);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.PlanetID = new SelectList(db.Planets, "PlanetID", "PlanetName", moonVM.PlanetID);
            return View(moonVM);
        }

        // GET: Moon/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Moon moon = db.Moons.Find(id);
            if (moon == null)
            {
                return HttpNotFound();
            }
            ViewBag.PlanetID = new SelectList(db.Planets, "PlanetID", "PlanetID", moon.PlanetID);
            return View(moon);
        }

        // POST: Moon/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MoonID,PlanetID,Orbit,WorldType,DayLength,WorldSize,WorldGravity")] Moon moon)
        {
            if (ModelState.IsValid)
            {
                db.Entry(moon).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.PlanetID = new SelectList(db.Planets, "PlanetID", "PlanetID", moon.PlanetID);
            return View(moon);
        }

        // GET: Moon/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Moon moon = db.Moons.Find(id);
            if (moon == null)
            {
                return HttpNotFound();
            }
            return View(moon);
        }

        // POST: Moon/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Moon moon = db.Moons.Find(id);
            db.Moons.Remove(moon);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WorldsProject/WorldsProject/Controllers/PlanetController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WorldsProject.Models;
using WorldsProject.DAL;
using WorldsProject.ViewModels;

namespace WorldsProject.Controllers
{
    public class PlanetController : Controller
    {
        private PrimaryContext db = new PrimaryContext();

        // GET: Planet
        public ActionResult Index()
        {
            var planets = db.Planets.Include(p => p.StarSystem);
            return View(planets.ToList());
        }

        // GET: Planet/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Planet planet = db.Planets.Find(id);
            if (planet == null)
            {
                return HttpNotFound();
            }
            return View(planet);
        }

        // GET: Planet/Create
        public ActionResult Create()
        {
            ViewBag.StarSystemID = new SelectList(db.StarSystems, "StarSystemID", "StarName");
            return View();
        }

        // POST: Planet/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "PlanetID,StarSystemID,Orbit")] Planet planet)
        public ActionResult Create([Bind(Include = "StarSystemID,Orbit,WorldType,WorldSize,WorldGravity,DayLength")] Planet planetVM)
        {
            if (ModelState.IsValid)
            {
                Planet newPlanet = new Planet();

                newPlanet.StarSystemID = planetVM.StarSystemID;
                newPlanet.Orbit = planetVM.Orbit;

                newPlanet.WorldType = planetVM.WorldType;
                newPlanet.WorldSize = planetVM.WorldSize;
                newPlanet.WorldGravity = planetVM.WorldGravity;
                newPlanet.DayLength = planetVM.DayLength;

                //newPlanet.PlanetName = planetVM.inheritPlanetName();

                db.Planets.Add(newPlanet);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.StarSystemID = new SelectList(db.StarSystems, "StarSystemID", "StarName", planetVM.StarSystemID);
            return View(planetVM);
        }

        // GET: Planet/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Planet planet = db.Planets.Find(id);
            if (planet == null)
            {
                return HttpNotFound();
            }
            ViewBag.StarSystemID = new SelectList(db.StarSystems, "StarSystemID", "StarName", planet.StarSystemID);
            return View(planet);
        }

        // POST: Planet/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PlanetID,StarSystemID,Orbit,WorldType,DayLength,WorldSize,WorldGravity")] Planet planet)
        {
            if (ModelState.IsValid)
            {
                db.Entry(planet).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.StarSystemID = new SelectList(db.StarSystems, "StarSystemID", "StarName", planet.StarSystemID);
            return View(planet);
        }

        // GET: Planet/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Planet planet = db.Planets.Find(id);
            if (planet == null)
            {
                return HttpNotFound();
            }
            return View(planet);
        }

        // POST: Planet/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Planet planet = db.Planets.Find(id);
            db.Planets.Remove(planet);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WorldsProject/WorldsProject/Controllers/StarSystemController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WorldsProject.Models;
using WorldsProject.DAL;

namespace WorldsProject.Controllers
{
    public class StarSystemController : Controller
    {
        private IStarSystemRepository starsystemRepository;
        //private PrimaryContext db = new PrimaryContext();

        public StarSystemController() // Called by MVC framework
        {
            this.starsystemRepository = new StarSystemRepository(new PrimaryContext());
        }

        public StarSystemController(IStarSystemRepository starsystemRepository)
        {
            this.starsystemRepository = starsystemRepository;
        }

        // GET: StarSystem
        public ActionResult Index()
        {
            return View(starsystemRepository.GetStarSystems());
        }

        // GET: StarSystem/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            StarSystem starSystem = starsystemRepository.GetStarSystemByID((int)id);

            if (starSystem == null)
            {
                return HttpNotFound();
            }
            return View(starSystem);
        }

        // GET: StarSystem/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: StarSystem/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "StarSystemID,Xcoordinate,Ycoordinate,StarName,StarType")] StarSystem starsystemVM)
        {
            if (ModelState.IsValid)
            {
                StarSystem newStarSystem = new StarSystem();

                newStarSystem.Xcoordinate = starsystemVM.Xcoordinate;
                newStarSystem.Ycoordinate = starsystemVM.Ycoordinate;

                newStarSystem.StarName = starsystemVM.StarName;
                newStarSystem.StarType = starsystemVM.StarType;

                //db.StarSystems.Add(newStarSystem);
                starsystemRepository.InsertStarSystem(newStarSystem);
                //db.SaveChanges();
                starsystemRepository.Save();
                return RedirectToAction("Index");
            }

            return View(starsystemVM);
        }

        // GET: StarSystem/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //StarSystem starSystem = db.StarSystems.Find(id);
            StarSystem starSystem = starsystemRepository.GetStarSystemByID((int)id);
            if (starSystem == null)
            {
                return HttpNotFound();
            }
            return View(starSystem);
        }

        // POST: StarSystem/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "StarSystemID,Xcoordinate,Ycoordinate,StarName,StarType")] StarSystem starSystem)
        {
            if (ModelState.IsValid)
            {
                //db.Entry(starSystem).State = EntityState.Modified;
                starsystemRepository.UpdateStarSystem(starSystem);
                //db.SaveChanges();
                starsystemRepository.Save();
                return RedirectToAction("Index");
            }
            return View(starSystem);
        }

        // GET: StarSystem/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //StarSystem starSystem = db.StarSystems.Find(id);
            StarSystem starSystem = starsystemRepository.GetStarSystemByID((int)id);
            if (starSystem == null)
            {
                return HttpNotFound();
            }
            return View(starSystem);
        }

        // POST: StarSystem/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            //StarSystem starSystem = db.StarSystems.Find(id);
            //db.StarSystems.Remove(starSystem);
            starsystemRepository.DeleteStarSystem(id);
            //db.SaveChanges();
            starsystemRepository.Save();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                starsystemRepository.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WorldsProject/WorldsProject/Views/Planet/Create.cshtml
@model WorldsProject.Models.Planet

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Planet</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.StarSystemID, "Star System", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StarSystemID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StarSystemID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Orbit, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Orbit, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Orbit, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WorldType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WorldType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.WorldType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DayLength, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DayLength, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DayLength, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WorldSize, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WorldSize, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.WorldSize, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WorldGravity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WorldGravity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.WorldGravity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WorldsProject/WorldsProject/Views/Planet/Delete.cshtml
@model WorldsProject.Models.Planet

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h3>Planet</h3>
    @{ Model.PlanetName = Model.inheritPlanetName(); }
    <h4>
        @Html.DisplayFor(model => model.PlanetName)
    </h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Star
        </dt>
        <dd>
            @Html.ActionLink(Model.StarSystem.StarName, "Details", "StarSystem", new { id = Model.StarSystem.StarSystemID }, null)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Orbit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Orbit)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WorldType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WorldType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DayLength)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DayLength)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WorldSize)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WorldSize)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WorldGravity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WorldGravity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Moons)
        </dt>
        @foreach (var m in Model.Moons)
        {
            m.MoonName = m.inheritMoonName(m.Orbit, m.Planet.Orbit, m.Planet.StarSystem.StarName);

            <dd>
                @Html.ActionLink(m.MoonName, "Details", "Moon", new { id = m.MoonID }, null)
            </dd>
        }

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WorldsProject/WorldsProject/Views/Planet/Details.cshtml
@model WorldsProject.Models.Planet

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h3>Planet</h3>
        @{ Model.PlanetName = Model.inheritPlanetName(); }
    <h4>
        @Html.DisplayFor(model => model.PlanetName)
    </h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Star
        </dt>
        <dd>
            @Html.ActionLink(Model.StarSystem.StarName, "Details", "StarSystem", new { id = Model.StarSystem.StarSystemID }, null)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Orbit)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Orbit)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WorldType)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.WorldType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DayLength)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DayLength)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WorldSize)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.WorldSize)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WorldGravity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WorldGravity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Moons)
        </dt>

        @foreach (var m in Model.Moons)
        {
            m.MoonName = m.inheritMoonName();
            
            <dd>
                @Html.ActionLink(m.MoonName, "Details", "Moon", new { id = m.MoonID }, null)
            </dd>
        }
    </dl>
</div>
<p>
    @Html.ActionLink("Back to List", "Index") |
    @Html.ActionLink("Edit", "Edit", new { id = Model.PlanetID }) |
    @Html.ActionLink("Delete", "Delete", new { id = Model.PlanetID })
</p>

WorldsProject/WorldsProject/Views/Planet/Edit.cshtml
@model WorldsProject.Models.Planet

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h3>Planet</h3>
        @{ Model.PlanetName = Model.inheritPlanetName(); }
        <h4>
            @Html.DisplayFor(model => model.PlanetName)
        </h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.PlanetID)

        <div class="form-group">
            @Html.LabelFor(model => model.StarSystemID, "StarSystemID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StarSystemID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StarSystemID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Orbit, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Orbit, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Orbit, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WorldType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WorldType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.WorldType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DayLength, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DayLength, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DayLength, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WorldSize, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WorldSize, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.WorldSize, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WorldGravity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WorldGravity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.WorldGravity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WorldsProject/WorldsProject/Views/Planet/Index.cshtml
@model IEnumerable<WorldsProject.Models.Planet>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            Planet Names
        </th>
        <th>
            @Html.DisplayNameFor(model => model.WorldType)
        </th>
        <th>
            Moons
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @{ item.PlanetName = item.inheritPlanetName(); }

            @Html.ActionLink(item.PlanetName, "Details", new { id = item.PlanetID }) 
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.WorldType)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Moons.Count)
        </td>
    </tr>
}

</table>