WorldsProject/WorldsProject/Models/StarSystem.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace WorldsProject.Models
{
    public class StarSystem
    {
        
        public int StarSystemID { get; set; } //Primary Key
   
        //[MinLength(8, ErrorMessage="Star coordinates must be 8 digits long and can be negative.")]
        public int Xcoordinate { get; set; }

        //[MinLength(8, ErrorMessage = "Star coordinates must be 8 digits long and can be negative.")]
        public int Ycoordinate { get; set; }

        //[MaxLength(50, ErrorMessage="Star names cannot exceed 50 characters.")]
        public string StarName { get; set; }

        //[MaxLength(12, ErrorMessage="Star types cannot exceed 12 characters.")]
        public string StarType { get; set; } //Fluff

        public virtual ICollection<Planet> Planets { get; set; } //foreign key to planets
    }
}

WorldsProject/WorldsProject/Controllers/PlanetController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WorldsProject.Models;
using WorldsProject.DAL;
using WorldsProject.ViewModels;

namespace WorldsProject.Controllers
{
    public class PlanetController : Controller
    {
        private PrimaryContext db = new PrimaryContext();

        // GET: Planet
        public ActionResult Index()
        {
            var planets = db.Planets.Include(p => p.StarSystem);
            return View(planets.ToList());
        }

        // GET: Planet/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Planet planet = db.Planets.Find(id);
            if (planet == null)
            {
                return HttpNotFound();
            }
            return View(planet);
        }

        // GET: Planet/Create
        public ActionResult Create()
        {
            ViewBag.StarSystemID = new SelectList(db.StarSystems, "StarSystemID", "StarName");
            return View();
        }

        // POST: Planet/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "PlanetID,StarSystemID,Orbit")] Planet planet)
        public ActionResult Create([Bind(Include = "StarSystemID,Orbit,WorldType,WorldSize,WorldGravity,DayLength")] Planet planetVM)
        {
            if (ModelState.IsValid)
            {
                Planet newPlanet = new Planet();

                newPlanet.StarSystemID = planetVM.StarSystemID;
                newPlanet.Orbit = planetVM.Orbit;

                newPlanet.WorldType = planetVM.WorldType;
                newPlanet.WorldSize = planetVM.WorldSize;
                newPlanet.WorldGravity = planetVM.WorldGravity;
                newPlanet.DayLength = planetVM.DayLength;

                //newPlanet.PlanetName = planetVM.inheritPlanetName();

                db.Planets.Add(newPlanet);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.StarSystemID = new SelectList(db.StarSystems, "StarSystemID", "StarName", planetVM.StarSystemID);
            return View(planetVM);
        }

        // GET: Planet/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Planet planet = db.Planets.Find(id);
            if (planet == null)
            {
                return HttpNotFound();
            }
            ViewBag.StarSystemID = new SelectList(db.StarSystems, "StarSystemID", "StarName", planet.StarSystemID);
            return View(planet);
        }

        // POST: Planet/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PlanetID,StarSystemID,Orbit,WorldType,DayLength,WorldSize,WorldGravity")] Planet planet)
        {
            if (ModelState.IsValid)
            {
                db.Entry(planet).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.StarSystemID = new SelectList(db.StarSystems, "StarSystemID", "StarName", planet.StarSystemID);
            return View(planet);
        }

        // GET: Planet/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Planet planet = db.Planets.Find(id);
            if (planet == null)
            {
                return HttpNotFound();
            }
            return View(planet);
        }

        // POST: Planet/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Planet planet = db.Planets.Find(id);
            db.Planets.Remove(planet);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WorldsProject/WorldsProject/Controllers/StarSystemController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WorldsProject.Models;
using WorldsProject.DAL;

namespace WorldsProject.Controllers
{
    public class StarSystemController : Controller
    {
        private IStarSystemRepository starsystemRepository;
        //private PrimaryContext db = new PrimaryContext();

        public StarSystemController() // Called by MVC framework
        {
            this.starsystemRepository = new StarSystemRepository(new PrimaryContext());
        }

        public StarSystemController(IStarSystemRepository starsystemRepository)
        {
            this.starsystemRepository = starsystemRepository;
        }

        // GET: StarSystem
        public ActionResult Index()
        {
            return View(starsystemRepository.GetStarSystems());
        }

        // GET: StarSystem/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            StarSystem starSystem = starsystemRepository.GetStarSystemByID((int)id);

            if (starSystem == null)
            {
                return HttpNotFound();
            }
            return View(starSystem);
        }

        // GET: StarSystem/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: StarSystem/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "StarSystemID,Xcoordinate,Ycoordinate,StarName,StarType")] StarSystem starsystemVM)
        {
            if (ModelState.IsValid)
            {
                StarSystem newStarSystem = new StarSystem();

                newStarSystem.Xcoordinate = starsystemVM.Xcoordinate;
                newStarSystem.Ycoordinate = starsystemVM.Ycoordinate;

                newStarSystem.StarName = starsystemVM.StarName;
                newStarSystem.StarType = starsystemVM.StarType;

                //db.StarSystems.Add(newStarSystem);
                starsystemRepository.InsertStarSystem(newStarSystem);
                //db.SaveChanges();
                starsystemRepository.Save();
                return RedirectToAction("Index");
            }

            return View(starsystemVM);
        }

        // GET: StarSystem/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //StarSystem starSystem = db.StarSystems.Find(id);
            StarSystem starSystem = starsystemRepository.GetStarSystemByID((int)id);
            if (starSystem == null)
            {
                return HttpNotFound();
            }
            return View(starSystem);
        }

        // POST: StarSystem/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "StarSystemID,Xcoordinate,Ycoordinate,StarName,StarType")] StarSystem starSystem)
        {
            if (ModelState.IsValid)
            {
                //db.Entry(starSystem).State = EntityState.Modified;
                starsystemRepository.UpdateStarSystem(starSystem);
                //db.SaveChanges();
                starsystemRepository.Save();
                return RedirectToAction("Index");
            }
            return View(starSystem);
        }

        // GET: StarSystem/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //StarSystem starSystem = db.StarSystems.Find(id);
            StarSystem starSystem = starsystemRepository.GetStarSystemByID((int)id);
            if (starSystem == null)
            {
                return HttpNotFound();
            }
            return View(starSystem);
        }

        // POST: StarSystem/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            //StarSystem starSystem = db.StarSystems.Find(id);
            //db.StarSystems.Remove(starSystem);
            starsystemRepository.DeleteStarSystem(id);
            //db.SaveChanges();
            starsystemRepository.Save();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                starsystemRepository.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WorldsProject/WorldsProject/Views/StarSystem/Create.cshtml
@model WorldsProject.Models.StarSystem

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>StarSystem</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.StarName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StarName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StarName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Xcoordinate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Xcoordinate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Xcoordinate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ycoordinate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ycoordinate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ycoordinate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StarType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StarType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StarType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WorldsProject/WorldsProject/Views/StarSystem/Delete.cshtml
@model WorldsProject.Models.StarSystem

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h3>Star System</h3>
    <h4>
        @Html.DisplayFor(model => model.StarName)
    </h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.StarName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StarName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Xcoordinate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Xcoordinate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ycoordinate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ycoordinate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StarType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StarType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Planets)
        </dt>

        @foreach (var p in Model.Planets)
        {
            p.PlanetName = p.inheritPlanetName();

            <dd>
                @Html.ActionLink(p.PlanetName, "Details", "Planet", new { id = p.PlanetID }, null)
            </dd>
        }

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WorldsProject/WorldsProject/Views/StarSystem/Details.cshtml
@model WorldsProject.Models.StarSystem 
@*Strongly typed*@

@{
    ViewBag.Title = "Details";
}
<h2>Details</h2>

<div>
    <h3>Star System</h3> 
    <h4>
        @Html.DisplayFor(model => model.StarName)
    </h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Xcoordinate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Xcoordinate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ycoordinate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ycoordinate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StarType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StarType)
        </dd>
        
        <dt>
            @Html.DisplayNameFor(model => model.Planets)
        </dt>

        @foreach (var p in Model.Planets)
        {
                p.PlanetName = p.inheritPlanetName(); 
            
            <dd>
                @Html.ActionLink(p.PlanetName,"Details","Planet", new { id = p.PlanetID }, null)
            </dd>
        }

    </dl>

</div>
<p>
    @Html.ActionLink("Back to List", "Index") |
    @Html.ActionLink("Edit", "Edit", new { id = Model.StarSystemID }) |
    @Html.ActionLink("Delete", "Delete", new { id = Model.StarSystemID })
    
</p>

WorldsProject/WorldsProject/Views/StarSystem/Edit.cshtml
@model WorldsProject.Models.StarSystem

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h3>Star System</h3>
        <h4>
            @Html.DisplayFor(model => model.StarName)
        </h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.StarSystemID)

        <div class="form-group">
            @Html.LabelFor(model => model.StarName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StarName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StarName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Xcoordinate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Xcoordinate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Xcoordinate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ycoordinate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ycoordinate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ycoordinate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StarType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StarType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StarType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WorldsProject/WorldsProject/Views/StarSystem/Index.cshtml
@model IEnumerable<WorldsProject.Models.StarSystem>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.StarName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Xcoordinate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ycoordinate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StarType)
        </th>
        <th>
            Planets
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.ActionLink(item.StarName, "Details", new { id = item.StarSystemID }) 
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Xcoordinate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Ycoordinate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StarType)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Planets.Count)
        </td>
    </tr>
}

</table>